M48
; DRILL file {KiCad 9.0.7} date 2026-01-18T00:15:32-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-18T00:15:32-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.900
%
G90
G05
T1
X153.5Y-91.5
T2
X147.3Y-103.0
X160.0Y-103.0
T3
X124.0Y-101.0
X124.0Y-103.54
M30
